include: package:lint/analysis_options.yaml


analyzer:
  exclude:
    - lib/logic/debug/app_bloc_observer.dart
    - lib/core/themes/app_theme.dart
    - lib/packages
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.chopper.dart

  errors:
    todo: warning
    
    require_trailing_commas: ignore
    avoid_dynamic_calls: ignore
    use_build_context_synchronously: ignore
    always_use_package_imports: ignore

    prefer_const_constructors: error